version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    groups:
      npm-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
    groups:
      github-actions-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(ci)
